### ISSUE TITLE
Support loading external PageXML files

### ISSUE THREAD

**Issue by Baciccin** [OCR4all/LAREX#211]
Tesseract does a pretty good job at fully automatic segmentation. I was hoping I could do a first pass with that, via [tesseract-recognize](https://github.com/mauvilsa/tesseract-recognize), and then fix the results by loading the file directly in LAREX.

What I tried:
1. Started a project with OCR4all as normal and performed preprocessing.
2. Used `tesseract-recognize` on one of the images and put the output in OCR4all's `processing` directory.
3. Tried launching LAREX (via the ground truth prediction menu).

The problem is that LAREX doesn't seem to like the format produced by `tesseract-recognize` and gets stuck on the "loading" screen forever.

I am happy to provide example files (via email preferably)

**Comment by chreul** [comment]
You can send the examples to ocr4all@uni-wuerzburg.de
Furthermore, would you mind trying the same procedure using the respective [OCR-D](https://github.com/OCR-D) processor?

**Comment by Baciccin** [comment]
Thanks for taking a look!

I tried using `ocrd_tesserocr`, as you suggested. It also fails to load unfortunately. The command I used was:
```
ocrd process \
  'cis-ocropy-binarize -I OCR-D-IMG -O OCR-D-SEG-PAGE' \
  'tesserocr-segment-region -I OCR-D-SEG-PAGE -O OCR-D-SEG-BLOCK' \
  'tesserocr-segment-line -I OCR-D-SEG-BLOCK -O OCR-D-SEG-LINE'
```

I've emailed you both XLM files plus the image of the page.

**Comment by maxnth** [comment]
This error was probably caused by the problem described in #172 which was fixed in version 0.4 of LAREX. 
When using the latest version of LAREX the segmentation was successfully loaded into the Viewer for both `0001.xml` and `OCR-D-SEG-LINE_0001.xml`.

We'll most likely release version 0.4 of the OCR4all Docker image (containing version 0.4 of LAREX) within the next few hours.
If LAREX won't load the XML files after the update or any other problems occur, please let us know.

**Comment by Baciccin** [comment]
Thanks for releasing a new model so quickly! I am happy to confirm that LAREX is now able to see the line segmentation.

One problem remains, although perhaps I should open an issue on the OCR4all repository about it instead of here: OCR4all does not "see" the fact that line segmentation has been performed. In the "Overview" screen all pages have a red X for the Line segmentation column, so it won't allow me to perform recognition on any of the pages unfortunately. If it's easier I'll open an issue on the OCR4all main repo, let me know.

**Comment by Baciccin** [comment]
Moved discussion to https://github.com/OCR4all/OCR4all/issues/76
